extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project: ./tsconfig.json
overrides:
  - files:
      - vite.config.ts
      - '*.ts'
      - '.tsx'
    parserOptions:
      project: ./tsconfig.node.json
